return {
    enabled = true,
    prompt = "> ",
    icons = {
        files = {
            enabled = false, -- show file icons
        },
        keymaps = {
            nowait = ""
        },
        indent = {
            vertical    = "│ ",
            middle = "├╴",
            last   = "└╴",
        },
        undo = {
            saved   = "",
        },
        ui = {
            live        = "",
            hidden      = "",
            ignored     = "",
            follow      = "",
            selected    = "+ ",
            unselected  = "  ",
        },
        git = {
            commit = "",
        },
        diagnostics = {
            Error = "",
            Warn  = "",
            Hint  = "",
            Info  = "",
        },
        kinds = {
            Array         = "",
            Boolean       = "",
            Class         = "",
            Color         = "",
            Control       = "",
            Collapsed     = "",
            Constant      = "",
            Constructor   = "",
            Copilot       = "",
            Enum          = "",
            EnumMember    = "",
            Event         = "",
            Field         = "",
            File          = "",
            Folder        = "",
            Function      = "",
            Interface     = "",
            Key           = "",
            Keyword       = "",
            Method        = "",
            Module        = "",
            Namespace     = "",
            Null          = "",
            Number        = "",
            Object        = "",
            Operator      = "",
            Package       = "",
            Property      = "",
            Reference     = "",
            Snippet       = "",
            String        = "",
            Struct        = "",
            Text          = "",
            TypeParameter = "",
            Unit          = "",
            Unknown        = "",
            Value         = "",
            Variable      = "",
        },
    },
}
